const DATABASE_NAME = "@gameplay";

const COLLECTION_USERS = `${DATABASE_NAME}: user`;
const COLLECTION_APPOINTMENTS = `${DATABASE_NAME}: appoitments`;

export { COLLECTION_USERS, COLLECTION_APPOINTMENTS };
